-- Schema for the Verminord dashboard (`dash` schema).
-- This matches the production schema in the Supabase project
-- ftjxpivxeavxdgcfpsba exactly; used for local development/testing.
create schema if not exists dash;

create table if not exists dash.team (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null,
  access text not null,
  pw text
);

create table if not exists dash.systems (
  id text primary key,
  sort integer not null,
  status text not null default 'I drift'
);

create table if not exists dash.readings (
  id bigint generated by default as identity primary key,
  system text not null,
  date text not null,
  temp real not null,
  ph real not null,
  fukt real not null,
  for_l real not null default 0,
  notat text not null default '',
  avvik integer not null default 0,
  logged_by text not null default '',
  source text not null default ''
);

create table if not exists dash.tasks (
  id bigint generated by default as identity primary key,
  title text not null,
  sub text not null,
  tag text not null,
  tagcls text not null default '',
  who text not null,
  open integer not null default 1,
  descr text not null default ''
);

create table if not exists dash.projects (
  id bigint generated by default as identity primary key,
  col text not null,
  tag text not null,
  title text not null,
  descr text not null,
  who text not null,
  sort integer not null
);

create table if not exists dash.checklist (
  id bigint generated by default as identity primary key,
  project_id bigint not null,
  text text not null,
  done integer not null default 0,
  sort integer not null
);

create table if not exists dash.partners (
  id bigint generated by default as identity primary key,
  name text not null,
  type text not null,
  status text not null,
  tagcls text not null default '',
  next_step text not null,
  who text not null
);

create table if not exists dash.files (
  id bigint generated by default as identity primary key,
  name text not null,
  cat text not null,
  ver text not null,
  date text not null,
  size text not null,
  content bytea
);

create table if not exists dash.targets (
  metric text primary key,
  min real not null,
  max real not null
);

create table if not exists dash.meta (
  key text primary key,
  value text not null
);

create table if not exists dash.hygiene_imports (
  id bigint generated by default as identity primary key,
  filename text not null,
  imported_at timestamptz not null default now(),
  imported_by text not null default '',
  row_count integer not null default 0,
  note text not null default ''
);

create table if not exists dash.hygiene_readings (
  id bigint generated by default as identity primary key,
  import_id bigint not null,
  ts timestamptz not null,
  ch integer not null,
  temp real not null
);

create table if not exists dash.inbox (
  id bigint generated by default as identity primary key,
  gmail_id text not null unique,
  received_at timestamptz not null default now(),
  sender text not null default '',
  subject text not null default '',
  summary text not null default '',
  category text not null default 'Til info',
  link text not null default '',
  draft_url text not null default '',
  status text not null default 'open',
  source text not null default 'gmail',
  snippet text not null default '',
  is_starred boolean not null default false,
  priority text not null default 'medium',
  severity text not null default 'normal',
  draft_body text not null default '',
  created_at timestamptz not null default now()
);

-- The phone logger (log.verminord.app, the old verminord-app repo) writes
-- production readings here. In production this table already exists with RLS
-- policies; the stub lets a fresh local database create the view below.
create table if not exists public.logs (
  id uuid primary key default gen_random_uuid(),
  system text not null,
  date date not null,
  temperature numeric,
  moisture numeric,
  ph numeric,
  notes text,
  created_by text,
  created_at timestamptz not null default now(),
  feed_amount_liters numeric,
  source text
);

-- Single read path for readings: live public.logs + dashboard's own rows.
-- Full definition and rationale in migrations/001_readings_all.sql.
create or replace view dash.readings_all as
with t as (
  select
    (select min from dash.targets where metric = 'temp') as temp_min,
    (select max from dash.targets where metric = 'temp') as temp_max,
    (select min from dash.targets where metric = 'ph')   as ph_min,
    (select max from dash.targets where metric = 'ph')   as ph_max,
    (select min from dash.targets where metric = 'fukt') as fukt_min,
    (select max from dash.targets where metric = 'fukt') as fukt_max
)
select
  'd:' || r.id::text                       as id,
  r.id                                     as rid,
  r.system, r.date, r.temp, r.ph, r.fukt, r.for_l, r.notat,
  r.avvik, r.logged_by,
  r.source                                 as source,
  null::timestamptz                        as logged_at,
  (r.source <> 'sheets')                   as editable
from dash.readings r
where r.source <> 'sheets'
   or not exists (select 1 from public.logs l
                  where l.system = r.system and l.date::text = r.date)
union all
select
  'a:' || l.id::text                       as id,
  null::bigint                             as rid,
  l.system,
  to_char(l.date, 'YYYY-MM-DD')            as date,
  coalesce(l.temperature, 0)::real         as temp,
  coalesce(l.ph, 0)::real                  as ph,
  coalesce(l.moisture, 0)::real            as fukt,
  coalesce(l.feed_amount_liters, 0)::real  as for_l,
  coalesce(l.notes, '')                    as notat,
  case when (l.temperature is not null and (l.temperature < t.temp_min or l.temperature > t.temp_max))
         or (l.ph          is not null and (l.ph          < t.ph_min   or l.ph          > t.ph_max))
         or (l.moisture    is not null and (l.moisture    < t.fukt_min or l.moisture    > t.fukt_max))
       then 1 else 0 end                   as avvik,
  coalesce(nullif(split_part(l.created_by, '@', 1), ''), 'App') as logged_by,
  'app'                                    as source,
  l.created_at                             as logged_at,
  false                                    as editable
from public.logs l
cross join t;

-- In production the app's role needs read access (view owner reads the
-- underlying tables). Locally the role may not exist — grant conditionally.
do $$ begin
  if exists (select 1 from pg_roles where rolname = 'dash_app') then
    grant select on dash.readings_all to dash_app;
  end if;
end $$;
