-- Schema for the Verminord dashboard (`dash` schema).
-- This matches the production schema in the Supabase project
-- ftjxpivxeavxdgcfpsba exactly; used for local development/testing.
create schema if not exists dash;

create table if not exists dash.team (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null,
  access text not null,
  pw text
);

create table if not exists dash.systems (
  id text primary key,
  sort integer not null,
  status text not null default 'I drift'
);

create table if not exists dash.readings (
  id bigint generated by default as identity primary key,
  system text not null,
  date text not null,
  temp real not null,
  ph real not null,
  fukt real not null,
  for_l real not null default 0,
  notat text not null default '',
  avvik integer not null default 0,
  logged_by text not null default '',
  source text not null default ''
);

create table if not exists dash.tasks (
  id bigint generated by default as identity primary key,
  title text not null,
  sub text not null,
  tag text not null,
  tagcls text not null default '',
  who text not null,
  open integer not null default 1
);

create table if not exists dash.projects (
  id bigint generated by default as identity primary key,
  col text not null,
  tag text not null,
  title text not null,
  descr text not null,
  who text not null,
  sort integer not null
);

create table if not exists dash.checklist (
  id bigint generated by default as identity primary key,
  project_id bigint not null,
  text text not null,
  done integer not null default 0,
  sort integer not null
);

create table if not exists dash.partners (
  id bigint generated by default as identity primary key,
  name text not null,
  type text not null,
  status text not null,
  tagcls text not null default '',
  next_step text not null,
  who text not null
);

create table if not exists dash.files (
  id bigint generated by default as identity primary key,
  name text not null,
  cat text not null,
  ver text not null,
  date text not null,
  size text not null,
  content bytea
);

create table if not exists dash.targets (
  metric text primary key,
  min real not null,
  max real not null
);

create table if not exists dash.meta (
  key text primary key,
  value text not null
);

create table if not exists dash.hygiene_imports (
  id bigint generated by default as identity primary key,
  filename text not null,
  imported_at timestamptz not null default now(),
  imported_by text not null default '',
  row_count integer not null default 0,
  note text not null default ''
);

create table if not exists dash.hygiene_readings (
  id bigint generated by default as identity primary key,
  import_id bigint not null,
  ts timestamptz not null,
  ch integer not null,
  temp real not null
);

create table if not exists dash.inbox (
  id bigint generated by default as identity primary key,
  gmail_id text not null unique,
  received_at timestamptz not null default now(),
  sender text not null default '',
  subject text not null default '',
  summary text not null default '',
  category text not null default 'Til info',
  link text not null default '',
  draft_url text not null default '',
  status text not null default 'open',
  created_at timestamptz not null default now()
);
