-- 005 — connector health, 5-year log retention, autologger ingest, weekly routines.
--
-- Four independent concerns, one migration because they share the same
-- deploy window. Every statement is idempotent; re-running is safe.
--
-- Apply with:
--   psql "$DASH_DATABASE_URL" -f dash-scripts/migrations/005_health_retention_sensors_routines.sql

begin;

-- ─────────────────────────────────────────────────────────────────────────
-- 1. CONNECTOR HEALTH
--
-- Every integration has died silently at least once (Gmail 12.07 → unnoticed
-- for 15 days; the Notion mirror sat 4 weeks stale while the UI claimed
-- "oppdateres hvert 10. min"). A connector that reports only into a log
-- nobody reads is the same as no connector.
--
-- expected_interval_min is what makes staleness *derivable* rather than
-- something a human has to notice: past that age with no success, the row
-- is stale whether or not anything threw an error. NULL = on-demand only
-- (never goes stale on its own; Gmail's "Synk nå", manual imports).
-- ─────────────────────────────────────────────────────────────────────────
create table if not exists dash.integrations (
  key                   text primary key,
  label                 text not null,
  expected_interval_min integer,
  last_ok_at            timestamptz,
  last_error            text,
  last_error_at         timestamptz,
  consecutive_failures  integer not null default 0,
  muted_until           timestamptz
);

insert into dash.integrations (key, label, expected_interval_min) values
  ('gmail',      'Innboks · Gmail',            null),
  ('applog',     'Produksjonslogg · appen',    60),
  ('autologger', 'Autologger · Ecowitt',       30),
  ('ai',         'AI-funksjoner',              null),
  ('hygiene',    'Hygienisering · Center 374', null)
on conflict (key) do nothing;

-- ─────────────────────────────────────────────────────────────────────────
-- 2. RETENTION — manual production logs
--
-- Norwegian rules require these logs to be retainable for at least 5 years.
-- The source code for this app was already lost once; the data must not be
-- able to follow it. Two guarantees:
--
--   a) an append-only archive that survives edits to the live tables, and
--   b) a trigger that refuses UPDATE/DELETE on the archive, so a wrong
--      query in a future session cannot quietly rewrite history.
--
-- The archive is written by trigger on dash.readings, not by application
-- code, so it cannot be bypassed by a route that forgets to call it.
-- ─────────────────────────────────────────────────────────────────────────
create table if not exists dash.readings_archive (
  archive_id  bigint generated by default as identity primary key,
  archived_at timestamptz not null default now(),
  op          text not null,              -- insert | update | delete
  row_id      bigint,
  system      text,
  date        text,
  temp        real,
  ph          real,
  fukt        real,
  for_l       real,
  notat       text,
  avvik       integer,
  logged_by   text,
  source      text
);

create index if not exists readings_archive_row_idx  on dash.readings_archive (row_id);
create index if not exists readings_archive_date_idx on dash.readings_archive (date);

create or replace function dash.archive_reading() returns trigger as $$
begin
  insert into dash.readings_archive
    (op, row_id, system, date, temp, ph, fukt, for_l, notat, avvik, logged_by, source)
  select
    lower(tg_op),
    r.id, r.system, r.date, r.temp, r.ph, r.fukt, r.for_l, r.notat, r.avvik, r.logged_by, r.source
  from (select coalesce(new, old).*) as r;
  return null;  -- AFTER trigger; return value is ignored
end;
$$ language plpgsql security definer;

drop trigger if exists readings_archive_trg on dash.readings;
create trigger readings_archive_trg
  after insert or update or delete on dash.readings
  for each row execute function dash.archive_reading();

-- The archive is write-once. Without this, "append-only" is a naming
-- convention rather than a property, and a 5-year record you can silently
-- rewrite is not a record.
create or replace function dash.archive_is_immutable() returns trigger as $$
begin
  raise exception 'dash.readings_archive er skrivebeskyttet (lovpålagt 5 års oppbevaring)';
end;
$$ language plpgsql;

drop trigger if exists readings_archive_immutable_trg on dash.readings_archive;
create trigger readings_archive_immutable_trg
  before update or delete on dash.readings_archive
  for each row execute function dash.archive_is_immutable();

-- Backfill whatever is already in the live table, once.
insert into dash.readings_archive
  (op, row_id, system, date, temp, ph, fukt, for_l, notat, avvik, logged_by, source)
select 'backfill', id, system, date, temp, ph, fukt, for_l, notat, avvik, logged_by, source
from dash.readings
where not exists (select 1 from dash.readings_archive where op = 'backfill');

-- ─────────────────────────────────────────────────────────────────────────
-- 3. AUTOLOGGER INGEST (Ecowitt WH52 → GW1200 → dashboard)
--
-- Deliberately NOT dash.readings. Seven sensors posting round the clock is
-- ~10k rows/day; mixing that into the hand-written production log would
-- bury the human entries and make "Skriv ut historikk" useless for an
-- inspector. Manual log = what a person observed. Sensor log = telemetry.
-- The two are joined at read time, never at write time.
--
-- Volume plan: raw rows are prunable (see hourly rollup below), EXCEPT rows
-- inside a hygienisering window — §19 needs fine resolution to prove
-- 70°C was held for 60 minutes, so those are pinned and never thinned.
-- ─────────────────────────────────────────────────────────────────────────
create table if not exists dash.sensor_map (
  channel    integer primary key,          -- WH52 soil channel, 1..16
  system     text not null,                -- 'CFT1', 'Wedge 1', 'Breeder Bin', …
  label      text not null default '',
  active     integer not null default 1
);

create table if not exists dash.sensor_readings (
  id          bigint generated by default as identity primary key,
  measured_at timestamptz not null,
  channel     integer not null,
  system      text not null,
  temp        real,                        -- soiltempN, °C (converted from °F on ingest)
  moisture    real,                        -- soilmoistureN, %
  ec          real,                        -- soilecN, µS/cm
  battery     real,
  rssi        integer,
  pinned      integer not null default 0,  -- 1 = inside a §19 window, never thinned
  raw         jsonb
);

-- One row per sensor per timestamp. The GW1200 retries on network failure,
-- so duplicate POSTs are normal and must be absorbed, not stored twice.
create unique index if not exists sensor_readings_dedup_idx
  on dash.sensor_readings (channel, measured_at);
create index if not exists sensor_readings_system_time_idx
  on dash.sensor_readings (system, measured_at desc);

-- Hourly rollup — this is the 5-year artifact. Raw rows can be thinned
-- after 90 days; these are kept indefinitely and are what gets exported
-- for documentation.
create table if not exists dash.sensor_hourly (
  system      text not null,
  channel     integer not null,
  hour        timestamptz not null,
  temp_min    real, temp_avg    real, temp_max    real,
  moist_min   real, moist_avg   real, moist_max   real,
  ec_min      real, ec_avg      real, ec_max      real,
  samples     integer not null default 0,
  primary key (system, channel, hour)
);

create or replace function dash.roll_up_sensor_hour(target_hour timestamptz)
returns integer as $$
declare
  touched integer;
begin
  insert into dash.sensor_hourly as h
    (system, channel, hour,
     temp_min, temp_avg, temp_max,
     moist_min, moist_avg, moist_max,
     ec_min, ec_avg, ec_max, samples)
  select
    system, channel, date_trunc('hour', measured_at),
    min(temp),     avg(temp),     max(temp),
    min(moisture), avg(moisture), max(moisture),
    min(ec),       avg(ec),       max(ec),
    count(*)
  from dash.sensor_readings
  where measured_at >= date_trunc('hour', target_hour)
    and measured_at <  date_trunc('hour', target_hour) + interval '1 hour'
  group by system, channel, date_trunc('hour', measured_at)
  on conflict (system, channel, hour) do update set
    temp_min = excluded.temp_min,   temp_avg = excluded.temp_avg,   temp_max = excluded.temp_max,
    moist_min = excluded.moist_min, moist_avg = excluded.moist_avg, moist_max = excluded.moist_max,
    ec_min = excluded.ec_min,       ec_avg = excluded.ec_avg,       ec_max = excluded.ec_max,
    samples = excluded.samples;
  get diagnostics touched = row_count;
  return touched;
end;
$$ language plpgsql;

-- ─────────────────────────────────────────────────────────────────────────
-- 4. RECURRING ROUTINES (weekly / daily checklist)
--
-- dash.checklist is project-scoped and one-shot — it cannot express "every
-- Monday". This is a separate, template-plus-instance model:
--
--   routines        the template ("Ukentlig runde")
--   routine_items   the steps on that template
--   routine_runs    one instance per occurrence (a given week/day)
--   routine_ticks   which step was completed, by whom, when
--
-- Ticks are per-run, so completing this week's round never mutates the
-- template and last week's record stays exactly as it was signed off.
-- That is also what makes the history defensible to an inspector.
-- ─────────────────────────────────────────────────────────────────────────
create table if not exists dash.routines (
  id        bigint generated by default as identity primary key,
  name      text not null,
  cadence   text not null default 'weekly',   -- daily | weekly
  active    integer not null default 1,
  sort      integer not null default 0
);

-- One row per line of UKEPLAN SOLO DRIFT.
--
-- weekday NULL  = part of the daily frame (every working day)
-- weekday 1..7  = that weekday's row in UKEN (1=Mon)
-- start_min     = minutes past midnight, so 07:30 is 450. The poster calls
--                 these "ankere, ikke lover" — they order the day and drive
--                 reminders, they are not a schedule anything is judged against.
--
-- drop_rank and never_drop encode "NÅR DAGEN RYKER" as data rather than as a
-- paragraph someone has to remember at 14:00 on a bad day: when the app is
-- told the day is slipping it can cut 1 → 2 → 3 in order and refuse to
-- surface anything flagged never_drop.
create table if not exists dash.routine_items (
  id         bigint generated by default as identity primary key,
  routine_id bigint not null references dash.routines(id) on delete cascade,
  block      text not null default '',       -- DAGLIG DRIFT, ORDEN, CEO 1, FYSISK, …
  text       text not null,
  detail     text not null default '',
  weekday    integer,
  start_min  integer,
  end_min    integer,
  drop_rank  integer,                        -- 1,2,3 = cut in this order
  never_drop integer not null default 0,     -- "Kuttes aldri"
  required   integer not null default 1,
  sort       integer not null default 0
);

create table if not exists dash.routine_runs (
  id           bigint generated by default as identity primary key,
  routine_id   bigint not null references dash.routines(id) on delete cascade,
  period_start date not null,                -- Monday of the week, or the day
  closed_at    timestamptz,
  closed_by    text,
  note         text not null default ''
);
create unique index if not exists routine_runs_period_idx
  on dash.routine_runs (routine_id, period_start);

create table if not exists dash.routine_ticks (
  run_id  bigint not null references dash.routine_runs(id) on delete cascade,
  item_id bigint not null references dash.routine_items(id) on delete cascade,
  done_at timestamptz not null default now(),
  done_by text not null default '',
  primary key (run_id, item_id)
);

-- FASTE REGLER and ÅPEN SAK. Kept as rows rather than hardcoded copy so the
-- plan stays "justeres etter behov" without a redeploy — the poster is v1 and
-- says so on its face.
create table if not exists dash.house_rules (
  id     bigint generated by default as identity primary key,
  kind   text not null default 'regel',   -- regel | apen_sak
  text   text not null,
  detail text not null default '',
  active integer not null default 1,
  sort   integer not null default 0
);

commit;
