-- 006 — extend 5-year retention to the phone logger's production log.
--
-- Migration 005 archived dash.readings and stopped there, which covered the
-- wrong table. The dashboard reads dash.readings_all, a view that UNIONs:
--
--   dash.readings   122 rows   entered through the dashboard
--   public.logs     420 rows   entered through log.verminord.app, 2025-07-07
--                              onward — a full year of daily logging
--
-- public.logs is the primary record and the one "Logg hver dag — loggen er
-- beviset overfor inspeksjonen" actually refers to. Archiving only
-- dash.readings would have produced a retention guarantee covering a quarter
-- of the data while looking complete.
--
-- The trigger is SECURITY DEFINER because public.logs is written by the
-- mobile app through the anon role, which has no grants in the dash schema;
-- without it every phone log would fail on the archive insert.
--
-- Apply with:
--   psql "$DASH_DATABASE_URL" -1 -f dash-scripts/migrations/006_archive_phone_logs.sql

create table if not exists dash.logs_archive (
  archive_id         bigint generated by default as identity primary key,
  archived_at        timestamptz not null default now(),
  op                 text not null,          -- insert | update | delete | backfill
  row_id             uuid,
  system             text,
  date               date,
  temperature        numeric,
  moisture           numeric,
  ph                 numeric,
  notes              text,
  created_by         text,
  created_at         timestamptz,
  feed_amount_liters numeric,
  source             text
);

create index if not exists logs_archive_row_idx  on dash.logs_archive (row_id);
create index if not exists logs_archive_date_idx on dash.logs_archive (date);

create or replace function dash.archive_log() returns trigger as $$
declare
  r public.logs%rowtype;
begin
  if tg_op = 'DELETE' then r := old; else r := new; end if;
  insert into dash.logs_archive
    (op, row_id, system, date, temperature, moisture, ph, notes,
     created_by, created_at, feed_amount_liters, source)
  values
    (lower(tg_op), r.id, r.system, r.date, r.temperature, r.moisture, r.ph,
     r.notes, r.created_by, r.created_at, r.feed_amount_liters, r.source);
  return null;
end;
$$ language plpgsql security definer;

drop trigger if exists logs_archive_trg on public.logs;
create trigger logs_archive_trg
  after insert or update or delete on public.logs
  for each row execute function dash.archive_log();

drop trigger if exists logs_archive_immutable_trg on dash.logs_archive;
create trigger logs_archive_immutable_trg
  before update or delete on dash.logs_archive
  for each row execute function dash.archive_is_immutable();

insert into dash.logs_archive
  (op, row_id, system, date, temperature, moisture, ph, notes,
   created_by, created_at, feed_amount_liters, source)
select 'backfill', l.id, l.system, l.date, l.temperature, l.moisture, l.ph,
       l.notes, l.created_by, l.created_at, l.feed_amount_liters, l.source
from public.logs l
where not exists (
  select 1 from dash.logs_archive a where a.row_id = l.id
);
