-- 007 — batch/harvest records.
--
-- Feeding (fôring) needed no new table: dash.readings_all.for_l already
-- carries it, because the phone logger and dashboard both capture feed
-- volume on the SAME entry as pH/temp/moisture — that pairing is deliberate
-- (Martin: "log in everytime on the same log as when taking ph, temp and
-- moisture"), not a gap to fill. What's missing is a place that reports it.
--
-- Batches are the other half — output rather than input — and genuinely
-- don't exist yet: harvesting isn't logged anywhere, on paper or otherwise.
-- Built ahead of the first real harvest so the page isn't empty the day
-- logging starts; the "batch_code" convention is deliberately unconstrained
-- (text, not an enum) since that scheme doesn't exist yet either.
--
-- Apply with:
--   psql "$DASH_DATABASE_URL" -1 -f dash-scripts/migrations/007_batches.sql

create table if not exists dash.batches (
  id           bigint generated by default as identity primary key,
  batch_code   text not null default '',
  system       text not null,           -- source CFT/Wedge/Breeder Bin
  started_at   date,
  harvested_at date,
  volume_l     real,
  weight_kg    real,
  moisture_pct real,
  notes        text not null default '',
  status       text not null default 'aktiv',  -- aktiv | høstet | arkivert
  created_by   text not null default '',
  created_at   timestamptz not null default now()
);

create index if not exists batches_system_idx on dash.batches (system);
create index if not exists batches_status_idx on dash.batches (status);
